schema_version = "1.0.0"
id = "Analysis_Toolkit"
version = "1.0.1"
name = "Analysis Toolkit"
tagline = "Measurement calculations, illuminance, distance, speed, and more"
maintainer = "Naoki Korematsu" 
type = "add-on"
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
tags = ["3D View", "Camera", "Lighting"]